project:
  type: website
  output-dir: docs
  
website:
  title: "ASAM135 Project"
  site-url: "https://juliatenorio.github.io/asamprojectfinal/"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "About"
        href: about.qmd
      - text: "Introduction"
        href: introduction.qmd
        
    right:
      - text: "Education (Julia)"
      - menu:
          - text: "Interviews"
          - text: "Interview – Mom"
            href: interviewmom.qmd
          - text: "Interview – Tita"
            href: interviewtita.qmd
          - text: "Photo Library"
          - text: "Aceron's Gallery"
            href: transcriptdocuments.qmd
          - text: "Dia's Gallery"
            href: diasphotos.qmd
          
      - text: "Migration (Alessi)"
      - menu: 
          - text: "Oral Histories"
            href: oralhistorites.qmd
          - text: "Photo Library"
            href: alessipictures.qmd

format:
  html:
    theme: sandstone
    theme-options:
      base-font: "Montserrat"
      heading-font: "Playfair Display"
    toc: true
    css: styles.css
